### ISSUE TITLE
 API for get current playing song's lyrics

### ISSUE THREAD

**Issue by xeonds** [Reverier-Xu/BitWave#8]
Can you add an api for fetch the current playing progress and lyrics for the current playing progress? 

> I want to create a kde/gnome widget for display desktop lyrics, which needs current playing progress and lyrics for the current playing progress
> Just like Yesplaymusic or LxMusic's desktop's api
> If the api can be called inside cli, it would be nice)

**Comment by Reverier-Xu** [comment]
The playing progress could be fetched from [MPRIS2 dbus protocol](https://specifications.freedesktop.org/mpris-spec/latest/).
You can try this from your terminal :)

```bash
# qdbus6 from qt6's toolbox, on some distributions you can use qdbus
qdbus6 org.mpris.MediaPlayer2.BitWave /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Position
qdbus6 org.mpris.MediaPlayer2.BitWave /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata

# try this to fetch all available MPRIS2 clients
qdbus6 | grep org.mpris.MediaPlayer2
```

it's recommended writing a common desktop lyrics widget instead of writing widgets only for some specific media players.

But sadly there are no protocols about OSD lyrics. [the existing osd lyrics project](https://github.com/osdlyrics/osdlyrics) self managed it's adapters for different media players. do you have some ideas about finding / designing a common API for that?
